default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV["DB_HOST"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>


development:
  primary:
    <<: *default
    database: quadrovagas-development
  queue:
    <<: *default
    database: quadrovagas-development_queue
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: quadrovagas-test

production:
  <<: *default
  database: quadrovagas-production